version: '3.8'

services:
  vite-dev:
    image: nextmovie
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - .:/movieapp:delegated
    - /movieapp/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
