# Image légère de Node.js
FROM node:18-alpine

# Définir le dossier de travail
WORKDIR /app

# Copier uniquement les fichiers nécessaires pour le cache des dépendances
COPY package.json package-lock.json ./

# Installer toutes les dépendances (y compris celles de dev)
RUN npm install

# Copier tout le code dans le conteneur
COPY . .

# Exposer le port Vite (Dev)
EXPOSE 5173

# Lancer l'application en mode dev avec hot-reload
CMD ["npm", "run", "dev", "--", "--host"]
